kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
# - name: build
#   pull: always
#   image: golang:1.14
#   commands:
#     - make generate
#   environment:
#     CGO_ENABLED: 0
#     GO111MODULE: on
#     GOPROXY: https://proxy.golang.org

- name: tests
  image: golang:1.14-alpine
  pull: always
  environment:
    TOKEN:
      from_secret: token
  commands:
    - 'apk update --no-cache && apk add bash curl make'
    - 'curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl'
    - 'chmod +x ./kubectl'
    - 'curl -X POST -H "Authorization: Bearer $TOKEN" http://212.47.229.210/api/v1/namespace > /tmp/kubeconfig.yaml'
    - 'export KUBECONFIG=/tmp/kubeconfig.yaml'
    - 'export NAMESPACE=$(cat /tmp/kubeconfig.yaml | grep namespace: | cut -c 16-) && echo $NAMESPACE'
    - 'make tests/manifests'
    - 'sh ./tests/e2e.sh deploy'
  when:
    branch:
    - drone
    event:
    - push
